name: Update Docs

on:
    push:
        branches:
            - master # Adjust branch name as needed

jobs:
    update_docs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Build and Generate Documentation
              run: cargo doc --no-deps

            - name: Clone Wiki Repository
              uses: actions/checkout@v2
              with:
                  repository: Enrico-Fabbri/FAS-RUST
                  path: wiki

            - name: Copy Documentation to Wiki
              run: cp -r target/doc/* wiki/

            - name: Commit and Push Changes
              working-directory: wiki
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add .
                  git commit -m "Update documentation"
                  git push https://${{ secrets.GH_TOKEN }}@github.com/Enrico-Fabbri/FAS-RUST
